events {}

http {
  resolver 127.0.0.11 valid=30s;
  resolver_timeout 5s;

  server {
    listen 80;

    location = / {
      add_header Content-Type application/json;
      return 200 '{"status":"ok","message":"MedStream API Gateway"}';
    }

    location /auth/ {
      set $backend auth-service:8000;
      rewrite ^/auth(/.*)$ $1 break;
      proxy_pass http://$backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /patients/ {
      set $backend patient-service:8000;
      rewrite ^/patients(/.*)$ $1 break;
      proxy_pass http://$backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /clinics/ {
      set $backend clinic-service:8000;
      rewrite ^/clinics(/.*)$ $1 break;
      proxy_pass http://$backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /appointments/ {
      set $backend appointment-service:8000;
      rewrite ^/appointments(/.*)$ $1 break;
      proxy_pass http://$backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ^~ /appointments/internal/ {
      return 403;
    }

    location /doctors/ {
      set $backend doctor-service:8000;
      rewrite ^/doctors(/.*)$ $1 break;
      proxy_pass http://$backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /telemedicine/ {
      set $backend telemedicine-service:8000;
      rewrite ^/telemedicine(/.*)$ $1 break;
      proxy_pass http://$backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ^~ /telemedicine/internal/ {
      return 403;
    }

    location ^~ /payments/internal/ {
      return 403;
    }

    location /payments/ {
      set $backend payment-service:8000;
      rewrite ^/payments(/.*)$ $1 break;
      proxy_pass http://$backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /notifications/ {
      set $backend notification-service:8000;
      rewrite ^/notifications(/.*)$ $1 break;
      proxy_pass http://$backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ^~ /clinics/internal/ {
      return 403;
    }
  }
}
