events {}

http {
  server {
    listen 80;

    location /auth/ {
      proxy_pass http://auth-service:8000/;
    }

    location /patients/ {
      proxy_pass http://patient-service:8000/;
    }

    location /clinics/ {
      proxy_pass http://clinic-service:8000/;
    }

    location /appointments/ {
      proxy_pass http://appointment-service:8000/;
    }

    location /payments/ {
      proxy_pass http://payment-service:8000/;
    }

    location /notifications/ {
      proxy_pass http://notification-service:8000/;
    }
  }
}
