services:
  api-gateway:
    image: nginx:1.27-alpine
    container_name: api-gateway
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - patient-service
      - clinic-service
      - appointment-service
      - payment-service
      - notification-service
    networks:
      - medstream-net

  postgres_db:
    image: postgres:15-alpine
    container_name: medstream_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - medstream-net

  auth-service:
    build: ./auth-service
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://dev_user:dev_password@postgres_db:5432/medstream_auth
    ports:
      - "8001:8000"
    networks:
      - medstream-net

  patient-service:
    build: ./patient-service
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://dev_user:dev_password@postgres_db:5432/medstream_clinic
    ports:
      - "8002:8000"
    networks:
      - medstream-net

  clinic-service:
    build: ./clinic-service
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://dev_user:dev_password@postgres_db:5432/medstream_clinic
    ports:
      - "8003:8000"
    networks:
      - medstream-net

  appointment-service:
    build: ./appointment-service
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://dev_user:dev_password@postgres_db:5432/medstream_clinic
    ports:
      - "8004:8000"
    networks:
      - medstream-net

  payment-service:
    build: ./payment-service
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://dev_user:dev_password@postgres_db:5432/medstream_payments
    ports:
      - "8005:8000"
    networks:
      - medstream-net

  notification-service:
    build: ./notification-service
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://dev_user:dev_password@postgres_db:5432/medstream_clinic
    ports:
      - "8006:8000"
    networks:
      - medstream-net

networks:
  medstream-net:
    driver: bridge

volumes:
  postgres_data:
